name: Run Tests On Push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.9.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.6
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          echo requirements installed
      - name: Run tests
        run: pytest 
